### ISSUE TITLE
`otbr-agent` restarting loop

### ISSUE THREAD

**Issue by giraz82** [b2un0/silabs-multipan-docker#3]
Hi, I'm facing the following issue:

```
otbr-agent[26035]: 38d.04:53:31.367 [I] Platform------: Backbone interface is configured to eth0 (2)
otbr-agent[26035]: 38d.04:53:31.367 [C] Platform------: platformConfigureTunDevice() at netif.cpp:1803: No such file or directory
2023-11-25 20:01:36 [INFO] otbr-agent ended with exit code 5 (signal 0)...
```

After that otbr-agent restarts and goes in an infinite loop.

Is this related to wrong backbone?
If I run `ifconfig` in my host I get:

```
eth0      Link encap:Ethernet  HWaddr 5A:36:E9:DC:DD:5D
          inet addr:10.69.107.7  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::5836:e9ff:fedc:dd5d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:12095 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8307 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2325833 (2.2 MiB)  TX bytes:27809828 (26.5 MiB)
```
And `10.69.107.7` is the correct ip.

If I run `ip a` I see:

```
2: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 5a:36:e9:dc:dd:5d brd ff:ff:ff:ff:ff:ff
    inet 10.69.107.7/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5836:e9ff:fedc:dd5d/64 scope link
       valid_lft forever preferred_lft forever
```

But If I set `BACKBONE_IF` to `eth0@if18` I got a different (worst I guess) error:

```
otbr-agent[390]: 38d.05:01:02.916 [D] Platform------: Wait response: tid=6 key=4619
otbr-agent[390]: 38d.05:01:02.917 [D] Platform------: Received spinel frame, flg:0x2, iid:2, tid:6, cmd:PROP_VALUE_IS, key:RADIO_CAPS, caps:255
otbr-agent[390]: 38d.05:01:02.929 [C] Platform------: platformBackboneInit() at backbone.cpp:62: Failure
2023-11-25 20:09:07 [INFO] otbr-agent ended with exit code 1 (signal 0)...
```

The host is a LXC on Proxmox.

Any idea to tackle the problem?

Thank you in advance.

**Comment by giraz82** [comment]
Ok, I think I'm missing the firs requirement: `working IPv6 in your LAN`
I think I'm missing ipv6 on my Proxmox machine. I will investigate on this.

Thank you for your work

**Comment by giraz82** [comment]
> any news on this topic? :) same error here

I didn't investigate any more, but I think that you have to be sure that you have a valid IPv6 configuration on your host.

**Comment by guba91** [comment]
Closed as completed because it has been fixed? :D

**Comment by b2un0** [comment]
There is nothing to fix. 

Is your container running privileged or in the host network?

**Comment by b2un0** [comment]
im able to reproduce this:
```
platformConfigureTunDevice() at netif.cpp:1803: No such file or directory
```

if i run the container without `privileged:true`

so im closing this right now.

**Comment by marcogazzola** [comment]
Hi, I'm getting the same issue and I've enabled both IPV6 on my network and privileged in docker compose. This is my configuration:

```yaml
  multipan:
    container_name: multipan
    image: ghcr.io/b2un0/silabs-multipan-docker:latest
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    **privileged: true**
    network_mode: host
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"

      NETWORK_DEVICES: 0

      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "eth0@if6"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"

      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8186"


      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108"

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "rcp-uart-802154-v4.3.1-zbdonglee-460800.gbl"
    ports:
      - "8081:8081"
      - "20108:20108"
      - "8186:8186"

```
![image](https://github.com/indomus/forum/assets/5739630/6f5e70ab-744e-4777-b10b-ccfd4568a5fb)

**Comment by marcogazzola** [comment]
> im able to reproduce this:
> 
> ```
> platformConfigureTunDevice() at netif.cpp:1803: No such file or directory
> ```
> 
> if i run the container without `privileged:true`
> 
> so im closing this right now.

Hi, I'm getting the same issue and I've enabled both IPV6 on my network and privileged in docker compose. This is my configuration:

```yaml
  multipan:
    container_name: multipan
    image: ghcr.io/b2un0/silabs-multipan-docker:latest
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: always
    **privileged: true**
    network_mode: host
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data/:/data
    environment:
      # OCPD environment variables
      DEVICE: "/dev/ttyACM0"
      BAUDRATE: "460800"
      CPCD_TRACE: "false"
      FLOW_CONTROL: "false"

      NETWORK_DEVICES: 0

      # OTBR-AGENT environment variables
      OTBR_ENABLE: 1
      BACKBONE_IF: "eth0@if6"
      OTBR_LOG_LEVEL: "debug"
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"

      # OTBR-WEB environment variables
      OTBR_WEB_PORT: "8186"


      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108"

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: "rcp-uart-802154-v4.3.1-zbdonglee-460800.gbl"
    ports:
      - "8081:8081"
      - "20108:20108"
      - "8186:8186"

```
![image](https://github.com/indomus/forum/assets/5739630/6f5e70ab-744e-4777-b10b-ccfd4568a5fb)
