### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by AnanasAPod** [b2un0/silabs-multipan-docker#6]
I can't get it to work. Unfortunately I can't find a solution. Maybe someone can help me.

Portainer LOG     

[09:08:15:892887] Info : ENCRYPTION IS DISABLED 
[09:08:15:892897] Info : Starting daemon in normal mode
[09:08:15:903723] Info : Connecting to Secondary...
[09:08:15:977322] Info : RX capability is 256 bytes
[09:08:15:977389] Info : Connected to Secondary
[09:08:15:978917] Info : Secondary Protocol v4
[09:08:15:980531] *** ASSERT *** : FATAL in function 'capabilities_checks' in file /usr/src/cpc-daemon/server_core/server_core.c at line #714 : UART flow control configuration mismatch between CPCd (enabled) and Secondary (disabled)
[09:08:16:981473] Info : Daemon exiting with status EXIT_FAILURE
Logger buffer size = 28672, highwater mark = 2474 : 8.63%. Lost logs : 0
2023-12-19 09:08:17 [INFO] CPC ended with exit code 1 (signal 0)...
2023-12-19 09:08:18 [INFO] Starting cpcd...
WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
FATAL in function 'capabilities_checks' in file /usr/src/cpc-daemon/server_core/server_core.c at line #714 : UART flow control configuration mismatch between CPCd (enabled) and Secondary (disabled)
[09:08:18:100017] Info : [CPCd v4.3.1.0] [Library API v3] [RCP Protocol v4]
[09:08:18:100095] Info : Git commit: 133b29678b3d0bc7578e098d2f46b4d5bcd2ebb4 / branch: 
[09:08:18:100108] Info : Sources hash: ff8300587e7e4ab1def7a89a272c0baef32f9eb3bff9b0ba06b94e655d652367
[09:08:18:100121] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[09:08:18:100149] Info : Reading cli arguments
[09:08:18:100163] Info : /usr/local/bin/cpcd 
[09:08:18:100545] Info : Reading configuration
[09:08:18:100557] Info :   file_path = /usr/local/etc/cpcd.conf
[09:08:18:100567] Info :   instance_name = cpcd_0
[09:08:18:100578] Info :   socket_folder = /dev/shm
[09:08:18:100588] Info :   operation_mode = MODE_NORMAL
[09:08:18:100598] Info :   use_encryption = false
[09:08:18:100609] Info :   binding_key_file = /root/.cpcd/binding.key
[09:08:18:100619] Info :   stdout_tracing = false
[09:08:18:100629] Info :   file_tracing = false
[09:08:18:100639] Info :   lttng_tracing = false
[09:08:18:100650] Info :   enable_frame_trace = false
[09:08:18:100660] Info :   traces_folder = /dev/shm/cpcd-traces
[09:08:18:100670] Info :   bus = UART
[09:08:18:100681] Info :   uart_baudrate = 460800
[09:08:18:100691] Info :   uart_hardflow = true
[09:08:18:100701] Info :   uart_file = /dev/ttyACM0
[09:08:18:100711] Info :   fu_recovery_pins_enabled = false
[09:08:18:100722] Info :   fu_connect_to_bootloader = false
[09:08:18:100732] Info :   fu_enter_bootloader = false
[09:08:18:100742] Info :   restart_cpcd = false
[09:08:18:100753] Info :   application_version_validation = false
[09:08:18:100763] Info :   print_secondary_versions_and_exit = false
[09:08:18:100773] Info :   use_noop_keep_alive = false
[09:08:18:100783] Info :   reset_sequence = true
[09:08:18:100794] Info :   stats_interval = 0
[09:08:18:100804] Info :   rlimit_nofile = 2000
[09:08:18:100814] Info : ENCRYPTION IS DISABLED 
[09:08:18:100824] Info : Starting daemon in normal mode
[09:08:18:111747] Info : Connecting to Secondary...
[09:08:18:185625] Info : RX capability is 256 bytes
[09:08:18:185716] Info : Connected to Secondary
[09:08:18:187420] Info : Secondary Protocol v4
[09:08:18:189170] *** ASSERT *** : FATAL in function 'capabilities_checks' in file /usr/src/cpc-daemon/server_core/server_core.c at line #714 : UART flow control configuration mismatch between CPCd (enabled) and Secondary (disabled)
[09:08:19:190085] Info : Daemon exiting with status EXIT_FAILURE
Logger buffer size = 28672, highwater mark = 2474 : 8.63%. Lost logs : 0
2023-12-19 09:08:19 [INFO] CPC ended with exit code 1 (signal 0)...
2023-12-19 09:08:20 [INFO] Starting cpcd...
WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
FATAL in function 'capabilities_checks' in file /usr/src/cpc-daemon/server_core/server_core.c at line #714 : UART flow control configuration mismatch between CPCd (enabled) and Secondary (disabled)
[09:08:20:310246] Info : [CPCd v4.3.1.0] [Library API v3] [RCP Protocol v4]
[09:08:20:310318] Info : Git commit: 133b29678b3d0bc7578e098d2f46b4d5bcd2ebb4 / branch: 
[09:08:20:310329] Info : Sources hash: ff8300587e7e4ab1def7a89a272c0baef32f9eb3bff9b0ba06b94e655d652367
[09:08:20:310346] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[09:08:20:310372] Info : Reading cli arguments
[09:08:20:310386] Info : /usr/local/bin/cpcd 
[09:08:20:310788] Info : Reading configuration
[09:08:20:310801] Info :   file_path = /usr/local/etc/cpcd.conf
[09:08:20:310811] Info :   instance_name = cpcd_0
[09:08:20:310821] Info :   socket_folder = /dev/shm
[09:08:20:310830] Info :   operation_mode = MODE_NORMAL
[09:08:20:310840] Info :   use_encryption = false
[09:08:20:310850] Info :   binding_key_file = /root/.cpcd/binding.key
[09:08:20:310860] Info :   stdout_tracing = false
[09:08:20:310870] Info :   file_tracing = false
[09:08:20:310879] Info :   lttng_tracing = false
[09:08:20:310889] Info :   enable_frame_trace = false
[09:08:20:310899] Info :   traces_folder = /dev/shm/cpcd-traces
[09:08:20:310909] Info :   bus = UART
[09:08:20:310918] Info :   uart_baudrate = 460800
[09:08:20:310928] Info :   uart_hardflow = true
[09:08:20:310938] Info :   uart_file = /dev/ttyACM0
[09:08:20:310948] Info :   fu_recovery_pins_enabled = false
[09:08:20:310958] Info :   fu_connect_to_bootloader = false
[09:08:20:310968] Info :   fu_enter_bootloader = false
[09:08:20:310977] Info :   restart_cpcd = false
[09:08:20:310987] Info :   application_version_validation = false
[09:08:20:310997] Info :   print_secondary_versions_and_exit = false
[09:08:20:311007] Info :   use_noop_keep_alive = false
[09:08:20:311017] Info :   reset_sequence = true
[09:08:20:311026] Info :   stats_interval = 0
[09:08:20:311036] Info :   rlimit_nofile = 2000

COMPOSE FILE:
```
version: "3.9"
services:
  multipan:
    container_name: multipan
    image: b2un0/silabs-multipan-docker:latest
    restart: unless-stopped
    privileged: true # don't change this !
    network_mode: host # don't change this !
    volumes:
      - ~/multipan/:/data
    environment:
      DEVICE: "/dev/ttyACM0" # only change if your have multiple devices
      BAUDRATE: "460800"
      FLOW_CONTROL: "true" # change to false if you not using SkyConnect

      BACKBONE_IF: "eno1" # change this to your network interface
      OTBR_REST_LISTEN_PORT: "8081" # use this within the HomeAssistant integration
      OTBR_WEB_PORT: "8086"

      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108" #

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0 # change to 1 for firmware update
      FIRMWARE: "NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl"
```

DEVICE LIST

![image](https://github.com/b2un0/silabs-multipan-docker/assets/76071534/4ea43c39-602a-4fb1-bb15-e76c425e9dbb)
